/*
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MediaEditable
 */
public class MediaEditableTest {
    private final MediaEditable model = new MediaEditable();

    /**
     * Model tests for MediaEditable
     */
    @Test
    public void testMediaEditable() {
        // TODO: test MediaEditable
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'modelId'
     */
    @Test
    public void modelIdTest() {
        // TODO: test modelId
    }

    /**
     * Test the property 'modelType'
     */
    @Test
    public void modelTypeTest() {
        // TODO: test modelType
    }

    /**
     * Test the property 'collectionName'
     */
    @Test
    public void collectionNameTest() {
        // TODO: test collectionName
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'fileName'
     */
    @Test
    public void fileNameTest() {
        // TODO: test fileName
    }

    /**
     * Test the property 'mimeType'
     */
    @Test
    public void mimeTypeTest() {
        // TODO: test mimeType
    }

    /**
     * Test the property 'disk'
     */
    @Test
    public void diskTest() {
        // TODO: test disk
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'manipulations'
     */
    @Test
    public void manipulationsTest() {
        // TODO: test manipulations
    }

    /**
     * Test the property 'customProperties'
     */
    @Test
    public void customPropertiesTest() {
        // TODO: test customProperties
    }

    /**
     * Test the property 'responsiveImages'
     */
    @Test
    public void responsiveImagesTest() {
        // TODO: test responsiveImages
    }

    /**
     * Test the property 'orderColumn'
     */
    @Test
    public void orderColumnTest() {
        // TODO: test orderColumn
    }

}
