/*
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProcessWebhookEditable
 */
public class ProcessWebhookEditableTest {
    private final ProcessWebhookEditable model = new ProcessWebhookEditable();

    /**
     * Model tests for ProcessWebhookEditable
     */
    @Test
    public void testProcessWebhookEditable() {
        // TODO: test ProcessWebhookEditable
    }

}
