/*
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.*;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProcessRequestTokenEditable
 */
public class ProcessRequestTokenEditableTest {
    private final ProcessRequestTokenEditable model = new ProcessRequestTokenEditable();

    /**
     * Model tests for ProcessRequestTokenEditable
     */
    @Test
    public void testProcessRequestTokenEditable() {
        // TODO: test ProcessRequestTokenEditable
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'dueAt'
     */
    @Test
    public void dueAtTest() {
        // TODO: test dueAt
    }

    /**
     * Test the property 'initiatedAt'
     */
    @Test
    public void initiatedAtTest() {
        // TODO: test initiatedAt
    }

    /**
     * Test the property 'riskchangesAt'
     */
    @Test
    public void riskchangesAtTest() {
        // TODO: test riskchangesAt
    }

}
