/*
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TaskAssignmentsEditable
 */
public class TaskAssignmentsEditableTest {
    private final TaskAssignmentsEditable model = new TaskAssignmentsEditable();

    /**
     * Model tests for TaskAssignmentsEditable
     */
    @Test
    public void testTaskAssignmentsEditable() {
        // TODO: test TaskAssignmentsEditable
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'processId'
     */
    @Test
    public void processIdTest() {
        // TODO: test processId
    }

    /**
     * Test the property 'processTaskId'
     */
    @Test
    public void processTaskIdTest() {
        // TODO: test processTaskId
    }

    /**
     * Test the property 'assignmentId'
     */
    @Test
    public void assignmentIdTest() {
        // TODO: test assignmentId
    }

    /**
     * Test the property 'assignmentType'
     */
    @Test
    public void assignmentTypeTest() {
        // TODO: test assignmentType
    }

}
