/*
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineObject4
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-04-24T19:12:37.315Z[GMT]")
public class InlineObject4 {
  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Integer userId;

  public static final String SERIALIZED_NAME_GROUP_ID = "group_id";
  @SerializedName(SERIALIZED_NAME_GROUP_ID)
  private Integer groupId;

  public static final String SERIALIZED_NAME_PERMISSIONS_NAMES = "permissions_names";
  @SerializedName(SERIALIZED_NAME_PERMISSIONS_NAMES)
  private List<Integer> permissionsNames = new ArrayList<Integer>();

  public InlineObject4 userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Id of the user whose permissions are configured
   * @return userId
  **/
  @ApiModelProperty(value = "Id of the user whose permissions are configured")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public InlineObject4 groupId(Integer groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Id of the group whose permissions are configured
   * @return groupId
  **/
  @ApiModelProperty(value = "Id of the group whose permissions are configured")
  public Integer getGroupId() {
    return groupId;
  }

  public void setGroupId(Integer groupId) {
    this.groupId = groupId;
  }

  public InlineObject4 permissionsNames(List<Integer> permissionsNames) {
    this.permissionsNames = permissionsNames;
    return this;
  }

  public InlineObject4 addPermissionsNamesItem(Integer permissionsNamesItem) {
    if (this.permissionsNames == null) {
      this.permissionsNames = new ArrayList<Integer>();
    }
    this.permissionsNames.add(permissionsNamesItem);
    return this;
  }

   /**
   * Update permissions
   * @return permissionsNames
  **/
  @ApiModelProperty(value = "Update permissions")
  public List<Integer> getPermissionsNames() {
    return permissionsNames;
  }

  public void setPermissionsNames(List<Integer> permissionsNames) {
    this.permissionsNames = permissionsNames;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject4 inlineObject4 = (InlineObject4) o;
    return Objects.equals(this.userId, inlineObject4.userId) &&
        Objects.equals(this.groupId, inlineObject4.groupId) &&
        Objects.equals(this.permissionsNames, inlineObject4.permissionsNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, groupId, permissionsNames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject4 {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    permissionsNames: ").append(toIndentedString(permissionsNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

