/*
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.*;
import org.openapitools.client.model.ProcessRequestTokenEditable;
import org.threeten.bp.OffsetDateTime;

/**
 * ProcessRequestToken
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-04-24T19:12:37.315Z[GMT]")
public class ProcessRequestToken {
  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_DUE_AT = "due_at";
  @SerializedName(SERIALIZED_NAME_DUE_AT)
  private OffsetDateTime dueAt = null;

  public static final String SERIALIZED_NAME_INITIATED_AT = "initiated_at";
  @SerializedName(SERIALIZED_NAME_INITIATED_AT)
  private OffsetDateTime initiatedAt;

  public static final String SERIALIZED_NAME_RISKCHANGES_AT = "riskchanges_at";
  @SerializedName(SERIALIZED_NAME_RISKCHANGES_AT)
  private OffsetDateTime riskchangesAt;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_PROCESS_ID = "process_id";
  @SerializedName(SERIALIZED_NAME_PROCESS_ID)
  private String processId;

  public static final String SERIALIZED_NAME_PROCESS_REQUEST_ID = "process_request_id";
  @SerializedName(SERIALIZED_NAME_PROCESS_REQUEST_ID)
  private String processRequestId;

  public static final String SERIALIZED_NAME_ELEMENT_ID = "element_id";
  @SerializedName(SERIALIZED_NAME_ELEMENT_ID)
  private String elementId;

  public static final String SERIALIZED_NAME_ELEMENT_TYPE = "element_type";
  @SerializedName(SERIALIZED_NAME_ELEMENT_TYPE)
  private String elementType;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public ProcessRequestToken userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * ProcessRequestToken is used to store the state of a token of the Nayra engine
   * @return userId
  **/
  @ApiModelProperty(value = "ProcessRequestToken is used to store the state of a token of the Nayra engine")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public ProcessRequestToken status(String status) {
    this.status = status;
    return this;
  }

   /**
   * ProcessRequestToken is used to store the state of a token of the Nayra engine
   * @return status
  **/
  @ApiModelProperty(value = "ProcessRequestToken is used to store the state of a token of the Nayra engine")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ProcessRequestToken dueAt(OffsetDateTime dueAt) {
    this.dueAt = dueAt;
    return this;
  }

   /**
   * ProcessRequestToken is used to store the state of a token of the Nayra engine
   * @return dueAt
  **/
  @ApiModelProperty(value = "ProcessRequestToken is used to store the state of a token of the Nayra engine")
  public OffsetDateTime getDueAt() {
    return dueAt;
  }

  public void setDueAt(OffsetDateTime dueAt) {
    this.dueAt = dueAt;
  }

  public ProcessRequestToken initiatedAt(OffsetDateTime initiatedAt) {
    this.initiatedAt = initiatedAt;
    return this;
  }

   /**
   * ProcessRequestToken is used to store the state of a token of the Nayra engine
   * @return initiatedAt
  **/
  @ApiModelProperty(value = "ProcessRequestToken is used to store the state of a token of the Nayra engine")
  public OffsetDateTime getInitiatedAt() {
    return initiatedAt;
  }

  public void setInitiatedAt(OffsetDateTime initiatedAt) {
    this.initiatedAt = initiatedAt;
  }

  public ProcessRequestToken riskchangesAt(OffsetDateTime riskchangesAt) {
    this.riskchangesAt = riskchangesAt;
    return this;
  }

   /**
   * ProcessRequestToken is used to store the state of a token of the Nayra engine
   * @return riskchangesAt
  **/
  @ApiModelProperty(value = "ProcessRequestToken is used to store the state of a token of the Nayra engine")
  public OffsetDateTime getRiskchangesAt() {
    return riskchangesAt;
  }

  public void setRiskchangesAt(OffsetDateTime riskchangesAt) {
    this.riskchangesAt = riskchangesAt;
  }

  public ProcessRequestToken id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ProcessRequestToken is used to store the state of a token of the Nayra engine
   * @return id
  **/
  @ApiModelProperty(value = "ProcessRequestToken is used to store the state of a token of the Nayra engine")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ProcessRequestToken processId(String processId) {
    this.processId = processId;
    return this;
  }

   /**
   * ProcessRequestToken is used to store the state of a token of the Nayra engine
   * @return processId
  **/
  @ApiModelProperty(value = "ProcessRequestToken is used to store the state of a token of the Nayra engine")
  public String getProcessId() {
    return processId;
  }

  public void setProcessId(String processId) {
    this.processId = processId;
  }

  public ProcessRequestToken processRequestId(String processRequestId) {
    this.processRequestId = processRequestId;
    return this;
  }

   /**
   * ProcessRequestToken is used to store the state of a token of the Nayra engine
   * @return processRequestId
  **/
  @ApiModelProperty(value = "ProcessRequestToken is used to store the state of a token of the Nayra engine")
  public String getProcessRequestId() {
    return processRequestId;
  }

  public void setProcessRequestId(String processRequestId) {
    this.processRequestId = processRequestId;
  }

  public ProcessRequestToken elementId(String elementId) {
    this.elementId = elementId;
    return this;
  }

   /**
   * ProcessRequestToken is used to store the state of a token of the Nayra engine
   * @return elementId
  **/
  @ApiModelProperty(value = "ProcessRequestToken is used to store the state of a token of the Nayra engine")
  public String getElementId() {
    return elementId;
  }

  public void setElementId(String elementId) {
    this.elementId = elementId;
  }

  public ProcessRequestToken elementType(String elementType) {
    this.elementType = elementType;
    return this;
  }

   /**
   * ProcessRequestToken is used to store the state of a token of the Nayra engine
   * @return elementType
  **/
  @ApiModelProperty(value = "ProcessRequestToken is used to store the state of a token of the Nayra engine")
  public String getElementType() {
    return elementType;
  }

  public void setElementType(String elementType) {
    this.elementType = elementType;
  }

  public ProcessRequestToken createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ProcessRequestToken is used to store the state of a token of the Nayra engine
   * @return createdAt
  **/
  @ApiModelProperty(value = "ProcessRequestToken is used to store the state of a token of the Nayra engine")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public ProcessRequestToken updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * ProcessRequestToken is used to store the state of a token of the Nayra engine
   * @return updatedAt
  **/
  @ApiModelProperty(value = "ProcessRequestToken is used to store the state of a token of the Nayra engine")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessRequestToken processRequestToken = (ProcessRequestToken) o;
    return Objects.equals(this.userId, processRequestToken.userId) &&
        Objects.equals(this.status, processRequestToken.status) &&
        Objects.equals(this.dueAt, processRequestToken.dueAt) &&
        Objects.equals(this.initiatedAt, processRequestToken.initiatedAt) &&
        Objects.equals(this.riskchangesAt, processRequestToken.riskchangesAt) &&
        Objects.equals(this.id, processRequestToken.id) &&
        Objects.equals(this.processId, processRequestToken.processId) &&
        Objects.equals(this.processRequestId, processRequestToken.processRequestId) &&
        Objects.equals(this.elementId, processRequestToken.elementId) &&
        Objects.equals(this.elementType, processRequestToken.elementType) &&
        Objects.equals(this.createdAt, processRequestToken.createdAt) &&
        Objects.equals(this.updatedAt, processRequestToken.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, status, dueAt, initiatedAt, riskchangesAt, id, processId, processRequestId, elementId, elementType, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessRequestToken {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    dueAt: ").append(toIndentedString(dueAt)).append("\n");
    sb.append("    initiatedAt: ").append(toIndentedString(initiatedAt)).append("\n");
    sb.append("    riskchangesAt: ").append(toIndentedString(riskchangesAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    processId: ").append(toIndentedString(processId)).append("\n");
    sb.append("    processRequestId: ").append(toIndentedString(processRequestId)).append("\n");
    sb.append("    elementId: ").append(toIndentedString(elementId)).append("\n");
    sb.append("    elementType: ").append(toIndentedString(elementType)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

