/*
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ScreensEditable
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-04-24T19:12:37.315Z[GMT]")
public class ScreensEditable {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_CONFIG = "config";
  @SerializedName(SERIALIZED_NAME_CONFIG)
  private String config;

  public ScreensEditable id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Class Screen
   * @return id
  **/
  @ApiModelProperty(value = "Class Screen")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ScreensEditable name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Class Screen
   * @return name
  **/
  @ApiModelProperty(value = "Class Screen")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ScreensEditable title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Class Screen
   * @return title
  **/
  @ApiModelProperty(value = "Class Screen")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public ScreensEditable type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Class Screen
   * @return type
  **/
  @ApiModelProperty(value = "Class Screen")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ScreensEditable description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Class Screen
   * @return description
  **/
  @ApiModelProperty(value = "Class Screen")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ScreensEditable config(String config) {
    this.config = config;
    return this;
  }

   /**
   * Class Screen
   * @return config
  **/
  @ApiModelProperty(value = "Class Screen")
  public String getConfig() {
    return config;
  }

  public void setConfig(String config) {
    this.config = config;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScreensEditable screensEditable = (ScreensEditable) o;
    return Objects.equals(this.id, screensEditable.id) &&
        Objects.equals(this.name, screensEditable.name) &&
        Objects.equals(this.title, screensEditable.title) &&
        Objects.equals(this.type, screensEditable.type) &&
        Objects.equals(this.description, screensEditable.description) &&
        Objects.equals(this.config, screensEditable.config);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, title, type, description, config);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScreensEditable {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

