/*
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ScriptsEditable;

/**
 * Scripts
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-04-24T19:12:37.315Z[GMT]")
public class Scripts {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  private String language;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_TEIMOUT = "teimout";
  @SerializedName(SERIALIZED_NAME_TEIMOUT)
  private Integer teimout;

  public Scripts id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Represents an Eloquent model of a Script
   * @return id
  **/
  @ApiModelProperty(value = "Represents an Eloquent model of a Script")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Scripts title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Represents an Eloquent model of a Script
   * @return title
  **/
  @ApiModelProperty(value = "Represents an Eloquent model of a Script")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Scripts description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Represents an Eloquent model of a Script
   * @return description
  **/
  @ApiModelProperty(value = "Represents an Eloquent model of a Script")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Scripts language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Represents an Eloquent model of a Script
   * @return language
  **/
  @ApiModelProperty(value = "Represents an Eloquent model of a Script")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public Scripts code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Represents an Eloquent model of a Script
   * @return code
  **/
  @ApiModelProperty(value = "Represents an Eloquent model of a Script")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Scripts teimout(Integer teimout) {
    this.teimout = teimout;
    return this;
  }

   /**
   * Represents an Eloquent model of a Script
   * @return teimout
  **/
  @ApiModelProperty(value = "Represents an Eloquent model of a Script")
  public Integer getTeimout() {
    return teimout;
  }

  public void setTeimout(Integer teimout) {
    this.teimout = teimout;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Scripts scripts = (Scripts) o;
    return Objects.equals(this.id, scripts.id) &&
        Objects.equals(this.title, scripts.title) &&
        Objects.equals(this.description, scripts.description) &&
        Objects.equals(this.language, scripts.language) &&
        Objects.equals(this.code, scripts.code) &&
        Objects.equals(this.teimout, scripts.teimout);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, description, language, code, teimout);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Scripts {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    teimout: ").append(toIndentedString(teimout)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

