/*
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import ProcessMaker_Client.ApiException;
import org.openapitools.client.model.Groups;
import org.openapitools.client.model.GroupsEditable;
import org.openapitools.client.model.InlineResponse2005;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GroupsApi
 */
@Ignore
public class GroupsApiTest {

    private final GroupsApi api = new GroupsApi();

    
    /**
     * Save a new group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createGroupTest() throws ApiException {
        GroupsEditable groupsEditable = null;
        Groups response = api.createGroup(groupsEditable);

        // TODO: test validations
    }
    
    /**
     * Delete a group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteGroupTest() throws ApiException {
        String groupId = null;
        Groups response = api.deleteGroup(groupId);

        // TODO: test validations
    }
    
    /**
     * Get single group by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGroupByIdTest() throws ApiException {
        String groupId = null;
        Groups response = api.getGroupById(groupId);

        // TODO: test validations
    }
    
    /**
     * Returns all groups that the user has access to
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGroupsTest() throws ApiException {
        String filter = null;
        String orderBy = null;
        String orderDirection = null;
        Integer perPage = null;
        String include = null;
        InlineResponse2005 response = api.getGroups(filter, orderBy, orderDirection, perPage, include);

        // TODO: test validations
    }
    
    /**
     * Update a group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateGroupTest() throws ApiException {
        String groupId = null;
        GroupsEditable groupsEditable = null;
        Groups response = api.updateGroup(groupId, groupsEditable);

        // TODO: test validations
    }
    
}
