/*
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import ProcessMaker_Client.ApiException;
import org.openapitools.client.model.InlineObject4;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PermissionsApi
 */
@Ignore
public class PermissionsApiTest {

    private final PermissionsApi api = new PermissionsApi();

    
    /**
     * Update the permissions of an user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processMakerHttpControllersApiPermissionControllerUpdateTest() throws ApiException {
        InlineObject4 inlineObject4 = null;
        api.processMakerHttpControllersApiPermissionControllerUpdate(inlineObject4);

        // TODO: test validations
    }
    
}
