/*
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import ProcessMaker_Client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProcessWebhooksApi
 */
@Ignore
public class ProcessWebhooksApiTest {

    private final ProcessWebhooksApi api = new ProcessWebhooksApi();

    
    /**
     * Save a new webhook for a start node
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createProcessWebhookTest() throws ApiException {
        Integer processId = null;
        String node = null;
        api.createProcessWebhook(processId, node);

        // TODO: test validations
    }
    
    /**
     * Delete (revoke) a webhook for a start node
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteProcessWebhookTest() throws ApiException {
        Integer processId = null;
        String node = null;
        api.deleteProcessWebhook(processId, node);

        // TODO: test validations
    }
    
    /**
     * Get the webhook for a start node
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProcessWebhookTest() throws ApiException {
        Integer processId = null;
        String node = null;
        api.getProcessWebhook(processId, node);

        // TODO: test validations
    }
    
}
