/*
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import ProcessMaker_Client.ApiException;
import org.openapitools.client.model.InlineResponse20015;
import org.openapitools.client.model.ScreenCategory;
import org.openapitools.client.model.ScreenCategoryEditable;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ScreenCategoriesApi
 */
@Ignore
public class ScreenCategoriesApiTest {

    private final ScreenCategoriesApi api = new ScreenCategoriesApi();

    
    /**
     * Save a new Screen Category
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createScreenCategoryTest() throws ApiException {
        ScreenCategoryEditable screenCategoryEditable = null;
        ScreenCategory response = api.createScreenCategory(screenCategoryEditable);

        // TODO: test validations
    }
    
    /**
     * Delete a screen category
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteScreenCategoryTest() throws ApiException {
        String screenCategoryId = null;
        ScreenCategory response = api.deleteScreenCategory(screenCategoryId);

        // TODO: test validations
    }
    
    /**
     * Returns all screens categories that the user has access to
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getScreenCategoriesTest() throws ApiException {
        String filter = null;
        String orderBy = null;
        String orderDirection = null;
        Integer perPage = null;
        String include = null;
        InlineResponse20015 response = api.getScreenCategories(filter, orderBy, orderDirection, perPage, include);

        // TODO: test validations
    }
    
    /**
     * Get single screen category by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getScreenCategoryByIdTest() throws ApiException {
        String screenCategoryId = null;
        ScreenCategory response = api.getScreenCategoryById(screenCategoryId);

        // TODO: test validations
    }
    
    /**
     * Update a screen Category
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateScreenCategoryTest() throws ApiException {
        String screenCategoryId = null;
        ScreenCategoryEditable screenCategoryEditable = null;
        ScreenCategory response = api.updateScreenCategory(screenCategoryId, screenCategoryEditable);

        // TODO: test validations
    }
    
}
