/*
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import ProcessMaker_Client.ApiException;
import org.openapitools.client.model.InlineResponse20018;
import org.openapitools.client.model.ProcessRequestToken;
import org.openapitools.client.model.ProcessRequestTokenEditable;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TasksApi
 */
@Ignore
public class TasksApiTest {

    private final TasksApi api = new TasksApi();

    
    /**
     * Returns all tasks that the user has access to
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTasksTest() throws ApiException {
        Integer processRequestId = null;
        String filter = null;
        String orderBy = null;
        String orderDirection = null;
        InlineResponse20018 response = api.getTasks(processRequestId, filter, orderBy, orderDirection);

        // TODO: test validations
    }
    
    /**
     * Update a task
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTaskTest() throws ApiException {
        String taskId = null;
        ProcessRequestTokenEditable processRequestTokenEditable = null;
        ProcessRequestToken response = api.updateTask(taskId, processRequestTokenEditable);

        // TODO: test validations
    }
    
}
